### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by zapaishchykova** [lucianoAvinas/lapgm#1]
Hi there!
Thanks for the great package. I have 3 questions:
1. Is it necessary for the lapgm to have both T1 and T2 sequences for the debiasing, or just T1 would be enough?

2. What is the best number of n_classes in` debias_obj.set_hyperparameters(tau=5e-5, n_classes=6, log_initialize=False)`? Do you have any heuristics on how to select that?

3. I have an error when running:
```
# Run debias procedure and take parameter output
params = debias_obj.estimate_parameters(brainweb_arr, print_tols=True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [48], line 2
      1 # Run debias procedure and take parameter output
----> 2 params = debias_obj.estimate_parameters(brainweb_arr, print_tols=True)

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/lapgm/lapgm_estim.py:143, in LapGM.estimate_parameters(self, image, bias_tol, max_em_iters, max_cg_iters, random_seed, print_tols, params_obj, custom_wgts)
    140 L = weight_laplacian(construct_dirichlet_lap(spat_ds_shape, True), wgts) / self.tau
    142 # calculate parameter estimates
--> 143 params = compute_bias_field(log_image, L, params, bias_tol, max_em_iters, print_tols)
    145 # define upscaler and apply
    146 upscaler = lambda img_ds, targ_shp, sc_lst: scale_and_pad(img_ds, targ_shp, sc_lst, 
    147                                                           self.scaling_order)

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/lapgm/bias_calc.py:33, in compute_bias_field(I_log, L, params, bias_tol, max_iters, print_tols)
     30 t = 0
     31 while params.Bdiff > bias_tol and t < max_iters:
     32     # E-step
---> 33     e_step(I_log, L, params)
     35     # M-step (partial): Gaussian params
     36     gauss_step(I_log, L, params)

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/lapgm/bias_calc.py:64, in e_step(I_log, L, params)
     62 I_BT = (I_log - params.B[ap.newaxis]).T
     63 for k in range(K):
---> 64     w[k] = params.pi[k] * multi_normal.pdf(I_BT, params.mu[k], params.Sigma[k],
     65                                            allow_singular=True)
     66 w = w/w.sum(axis=0)
     68 params.save('w', w)

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/lapgm/cupyx_mvn.py:27, in multivariate_normal.pdf(x, mean, cov, allow_singular)
     15 """Calculates probability density value for a specified multivariate normal.
     16 
     17 Args:
   (...)
     23 Returns array of length 'N' of probability density values.
     24 """
     25 dim = mean.shape[0]
---> 27 s, u = scipy.linalg.eigh(cp.asnumpy(cov), lower=True, check_finite=True)
     29 t = s.dtype.char.lower()
     30 factor = {'f': 1E3, 'd': 1E6}

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/scipy/linalg/_decomp.py:447, in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite, subset_by_index, subset_by_value, driver)
    443 if driver not in drv_str:
    444     raise ValueError('"{}" is unknown. Possible values are "None", "{}".'
    445                      ''.format(driver, '", "'.join(drv_str[1:])))
--> 447 a1 = _asarray_validated(a, check_finite=check_finite)
    448 if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    449     raise ValueError('expected square "a" matrix')

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/scipy/_lib/_util.py:287, in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok, as_inexact)
    285         raise ValueError('masked arrays are not supported')
    286 toarray = np.asarray_chkfinite if check_finite else np.asarray
--> 287 a = toarray(a)
    288 if not objects_ok:
    289     if a.dtype is np.dtype('O'):

File ~/miniconda3/envs/pycox310/lib/python3.10/site-packages/numpy/lib/function_base.py:627, in asarray_chkfinite(a, dtype, order)
    625 a = asarray(a, dtype=dtype, order=order)
    626 if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
--> 627     raise ValueError(
    628         "array must not contain infs or NaNs")
    629 return a

ValueError: array must not contain infs or NaNs
```

Unfortunately, I cannot share source MRI due to the data privacy, but for example:
`np.isnan(im).any(), np.isinf(im).any() `returns `(False,False)`
`np.isfinite(im).all() `returns `True`
and I have also tried  `im=np.nan_to_num(im).astype(float)`

**Comment by lucianoAvinas** [comment]
Hi thanks for trying out LapGM! To answer some of the questions:

1. LapGM can work in the single sequence setting, although a call to `to_sequence_array` is still necessary. This can be done by setting `input = lapgm.to_sequence_array([t1_data])`.

2. The best number may depend on the data at hand and the initialization method chosen. For clusters which are log-initialized, a low number of classes 4-6 seems to work best. For non-log initialized data, classes of 6-10 seem to work well. 
A good way to check whether redundant classes have been introduced is to observed the final estimated class map (a class map example shown in cell [#8] of image_correction.ipynb). If a dominant tissue group (or ambient space) is split between 2 or more classes, this may be an indication that there are too many classes for the current cluster initialization scheme.

3. It is hard to say what the issue is exactly, but it could be that some zeros have been incurred somewhere in the initialization process. I would first step through with a debugger to make sure no zeros were created inside the `fill_zeros_and_log` call inside of `LapGM.estimate_parameters`. This should not be the case for float-type data but it is something worth checking. 
If this error is occuring on optimization iteration 2 or beyond it could mean that the value of tau is too small and needs to be increased to possibly 1e-3 or 1e-1. Ultimately the issue seems to be with the intermediate variable `I_BT` so identifying whether `I_log` contains NaNs or `params.B` contains NaNs would help us as we go forward with this problem.
